all:
	../68000/a68k "Abs.asm" -o"Abs.hex" -s -n -rmal -q
	../68000/a68k "StrLen.asm" -o"StrLen.hex" -s -n -rmal -q
	../68000/a68k "SpaceCount.asm" -o"SpaceCount.hex" -s -n -rmal -q
	../68000/a68k "LowerCount.asm" -o"LowerCount.hex" -s -n -rmal -q
	../68000/a68k "AlphaCount.asm" -o"AlphaCount.hex" -s -n -rmal -q
	../68000/a68k "Atoui.asm" -o"Atoui.hex" -s -n -rmal -q

clean:
	rm *.hex
