all:
	../68000/a68k "Step_01.asm" -o"Step_01.hex" -s -n -rmal -q
	../68000/a68k "Step_02.asm" -o"Step_02.hex" -s -n -rmal -q
	../68000/a68k "Step_03.asm" -o"Step_03.hex" -s -n -rmal -q
	../68000/a68k "Step_04.asm" -o"Step_04.hex" -s -n -rmal -q
	../68000/a68k "Step_05.asm" -o"Step_05.hex" -s -n -rmal -q
	../68000/a68k "Step_06.asm" -o"Step_06.hex" -s -n -rmal -q

clean:
	rm *.hex
